// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATzbk9MGpuOPX8swWy0dDhR74VKR2Z1-Y',
    appId: '1:1037091360507:web:d88230c6d397084fd76a5e',
    messagingSenderId: '1037091360507',
    projectId: 'afed-ddfee',
    authDomain: 'afed-ddfee.firebaseapp.com',
    storageBucket: 'afed-ddfee.appspot.com',
    measurementId: 'G-F52N1KRWHF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOi4Ny4qf5SswSRWCBYL2JPcIYmQ7zbM4',
    appId: '1:1037091360507:android:d53be4e394f193a2d76a5e',
    messagingSenderId: '1037091360507',
    projectId: 'afed-ddfee',
    storageBucket: 'afed-ddfee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfascMiBnuclaiQh__8mKqBU2_gx6zasM',
    appId: '1:1037091360507:ios:d99d014661028fb8d76a5e',
    messagingSenderId: '1037091360507',
    projectId: 'afed-ddfee',
    storageBucket: 'afed-ddfee.appspot.com',
    iosClientId: '1037091360507-9nj7e6tui50rn73310jje2nrqog7eiae.apps.googleusercontent.com',
    iosBundleId: 'com.example.afed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfascMiBnuclaiQh__8mKqBU2_gx6zasM',
    appId: '1:1037091360507:ios:d99d014661028fb8d76a5e',
    messagingSenderId: '1037091360507',
    projectId: 'afed-ddfee',
    storageBucket: 'afed-ddfee.appspot.com',
    iosClientId: '1037091360507-9nj7e6tui50rn73310jje2nrqog7eiae.apps.googleusercontent.com',
    iosBundleId: 'com.example.afed',
  );
}
